name: 📝 Comment on Release

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  comment:
    name: Comment on Release
    if: github.repository == 'mcansh/release-comment-action'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📝 Comment on issues
        uses: ./
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
